# Generated by Django 4.0.4 on 2022-05-09 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, verbose_name='balance')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_number', models.CharField(max_length=250, null=True)),
                ('receiver_number', models.CharField(max_length=250, null=True)),
                ('amout', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESSFUL', 'SUCCESSFUL'), ('FAILED', 'FAILED')], max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('type_transaction', models.CharField(choices=[('AccountFunding', 'AccountFunding'), ('Transfert', 'Transfert'), ('Withdraw', 'Withdraw')], max_length=250)),
                ('operator', models.CharField(choices=[('MTN', 'MTN'), ('ORANGE', 'ORANGE')], max_length=50)),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='Wallet.wallet')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='Wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Mtn_API_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=350)),
                ('operator', models.CharField(choices=[('MTN', 'MTN'), ('ORANGE', 'ORANGE')], max_length=50)),
                ('api_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wallet.wallet')),
            ],
            options={
                'verbose_name': 'Mtn API Account',
                'verbose_name_plural': 'Mtn API Accounts',
            },
        ),
    ]
