# Generated by Django 4.0.4 on 2022-05-09 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amout',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='mtn_api_account',
            name='operator',
            field=models.CharField(choices=[('MTN', 'MTN'), ('ORANGE', 'ORANGE'), ('SPAY Account', 'SPAY Account')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='operator',
            field=models.CharField(choices=[('MTN', 'MTN'), ('ORANGE', 'ORANGE'), ('SPAY Account', 'SPAY Account')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='Wallet.wallet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='Wallet.wallet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
