# Generated by Django 4.0.4 on 2022-09-10 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0003_mtn_api_account_api_key_disb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mtn_api_account',
            name='api_key_disb',
        ),
    ]
