# Generated by Django 4.0.4 on 2022-09-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0004_remove_mtn_api_account_api_key_disb'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='cart_number',
            field=models.IntegerField(null=True),
        ),
    ]
