# Generated by Django 4.0.4 on 2022-09-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0005_wallet_cart_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='cart_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
