# Generated by Django 4.0.4 on 2022-04-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OAuth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalaccount',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='personalaccount',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=250),
        ),
    ]
